dist: trusty
jdk:
  - oraclejdk8
node_js:
  - node
cache: yarn
script:
  - yarn install
  - yarn test
  - cd $TRAVIS_BUILD_DIR/maven-cargo && ./mvnw --batch-mode verify
  - cd $TRAVIS_BUILD_DIR/gradle-docker && ./gradlew check
